databases:
  - name: lab5_blogpost_app_db
    databaseName: lab5_blogpost_app_db
    user: lab5_blogpost_app_db_user

services:
  - type: web
    name: lab5jannu
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn lab5jannu.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lab5_blogpost_app_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4